### ISSUE TITLE
ABC093_C

### ISSUE THREAD

**Issue by ababa831** [ababa893/atcoder_beginners#1]
## 問題名とリンク
[C Same Integers](https://atcoder.jp/contests/abc093/tasks/arc094_a)

## 解けない原因

わからん．

https://atcoder.jp/contests/abc093/submissions/9161627

想定するテストケースはほぼ潰したはずだが何か漏れている？

### 1種類の数字しか存在しない

すでに目的が達成されているので`print(0)`

#### 数字の小さい方が2つ
`1 1 3` + 1ずつ増やして大きい方に合わせる

#### 数字の大きい方が2つ

`1 3 3` (大きい数字と小さい数字の差分が偶数 -> 小さい方を+2ずつ増やせば大きい方にあう)
`1 4 4` (大きい数字と小さい数字の差分が奇数 -> 小さい方を+2ずつ増やしていき，大きい方を越した場合，大きかった方を+1ずつ調整して増やす)

### 3種類の数字が存在

`1 3 5` 一番大きい方に合わせて小さいもの2つを+1ずつ増やしていく，二番目に大きい数字が一番大きい数字と並んだら，一番小さい方を+2ずつ調整する．一番小さい方と大きい方の差分が偶数の場合は，そのまま+2していけば数字が合うが，奇数の場合は大きい方を越したあとに大きい2つの数字を+1増やす調整が追加で必要．

**Comment by ababa831** [comment]
極力解説を読まず自力でACまで到達したい

**Comment by ababa893** [comment]
https://github.com/ababa893/atcoder_beginners/blob/master/contest_093/c.py

**Comment by ababa831** [comment]
https://github.com/ababa893/atcoder_beginners/blob/master/contest_093/c.py

原因判明，`3種類の数字が存在`する場合のケアレスミスが原因．
対応完了したのでClose
